---
- name: Mount SMB share and copy folder on Windows host
  hosts: Test
  gather_facts: no
  tasks:

    - name: Create folder C:\temp\ansible if it does not exist
      win_file:
        path: C:\temp\ansible
        state: directory

    - name: Mount network share, copy folder, and unmount in same session
      win_shell: |
        net use Z: \\10.176.26.59\apps /user:global\85144917 "Start2025!@#"
        Copy-Item -Path 'Z:\WINDOWS 10\Andrija\Instalacije\vmwaretools' -Destination 'C:\temp\ansible\vmwaretools' -Recurse -Force
        net use Z: /delete
      args:
        executable: powershell.exe
