---
- name: Copy VMware ISO from network to local
  hosts: UPIS_Plate
  gather_facts: no
  vars:
    network_path: "\\\\10.176.26.59\\apps\\WINDOWS 10\\Andrija\\VMware-tools-windows-arm-13.0.0-24696409.iso"
    dest_path: "C:\\Temp\\VMware"

  tasks:
    - name: Ensure destination directory exists
      ansible.windows.win_file:
        path: "{{ dest_path }}"
        state: directory

    - name: Copy ISO using robocopy
      ansible.windows.win_command: >
        robocopy "{{ network_path | regex_replace('\\\\[^\\\\]+$', '') }}" "{{ dest_path }}" "{{ network_path | regex_replace('^.*\\\\', '') }}" /Z /NFL /NDL /NJH /NJS /NP
      register: robocopy_result
      ignore_errors: yes

    - name: Show robocopy output
      debug:
        var: robocopy_result.stdout_lines
