---
- name: Mount SMB share and copy folder on Windows host
  hosts: Test
  gather_facts: no
  tasks:

    - name: Create folder C:\temp\ansible if it does not exist
      win_file:
        path: C:\temp\ansible
        state: directory
      register: create_folder_output

    - name: Show output of folder creation
      debug:
        var: create_folder_output

    - name: Mount network share, copy folder, and unmount in same session
      win_shell: |
        net use Z: \\10.176.26.59\apps /user:global\85144917 "Start2025!@#"
        Copy-Item -Path 'Z:\WINDOWS 10\Andrija\Instalacije\vmwaretools' -Destination 'C:\temp\ansible\vmwaretools' -Recurse -Force
        net use Z: /delete
      args:
        executable: powershell.exe
      register: copy_output

    - name: Show PowerShell command output
      debug:
        var: copy_output.stdout_lines

    - name: Show PowerShell error output (if any)
      debug:
        var: copy_output.stderr_lines
