---
- name: Kreiraj AD grupu sa PowerShell-a lokalno preko Ansible-a
  hosts: Management_servers
  gather_facts: no
  tasks:
    - name: Kreiraj AD grupu ako ne postoji
      ansible.windows.win_shell: |
        Import-Module ActiveDirectory
        $groupName = "test"
        $ouPath = "OU=YU,OU=BAT Groups,DC=Global,DC=batgen,DC=com"
        $existingGroup = Get-ADGroup -LDAPFilter "(cn=$groupName)" -SearchBase $ouPath -ErrorAction SilentlyContinue

        if (-not $existingGroup) {
            New-ADGroup -Name $groupName `
                        -SamAccountName $groupName `
                        -GroupScope Global `
                        -GroupCategory Security `
                        -Path $ouPath
            Write-Host "✅ Grupa '$groupName' je uspešno kreirana u $ouPath"
        } else {
            Write-Host "ℹ Grupa '$groupName' već postoji u $ouPath"
        }
