---
- name: Kreiraj AD grupu sa PowerShell-a lokalno preko Ansible-a
  hosts: 	Management_Servers
  gather_facts: no

  tasks:
    - name: Proveri i kreiraj AD grupu
      ansible.windows.win_shell: |
        Import-Module ActiveDirectory

        $groupName = "test"
        $ouPath = "OU=YU,OU=BAT Groups,DC=Global,DC=batgen,DC=com"

        try {
            $group = Get-ADGroup -LDAPFilter "(cn=$groupName)" -SearchBase $ouPath -ErrorAction Stop
            Write-Output "EXISTS: Grupa '$groupName' već postoji."
        } catch {
            New-ADGroup -Name $groupName -SamAccountName $groupName -GroupScope Global -GroupCategory Security -Path $ouPath
            Write-Output "CREATED: Grupa '$groupName' je uspešno kreirana."
        }
      register: ad_group_result

    - name: Prikaži status grupe
      ansible.builtin.debug:
        msg: "{{ ad_group_result.stdout_lines }}"
