- name: Kreiraj AD grupu "test"
  hosts: Management_Servers
  gather_facts: no

  tasks:
    - name: Pokreni PowerShell komandu za kreiranje AD grupe
      ansible.windows.win_shell: |
        powershell -NoProfile -ExecutionPolicy Bypass -Command "& {
            Import-Module ActiveDirectory
            Start-Sleep -Seconds 2

            $groupName = 'test'
            $ouPath = 'OU=YU,OU=BAT Groups,DC=Global,DC=batgen,DC=com'
            $dc = '10.176.26.61'

            if (-not (Get-ADGroup -Server $dc -Filter \"Name -eq '$groupName'\" -SearchBase $ouPath -ErrorAction SilentlyContinue)) {
                New-ADGroup -Server $dc -Name $groupName -SamAccountName $groupName -GroupScope Global -GroupCategory Security -Path $ouPath
                Write-Output \"CREATED: Grupa '$groupName' je uspešno kreirana.\"
            } else {
                Write-Output \"EXISTS: Grupa '$groupName' već postoji.\"
            }
        }"
      register: ps_out

    - name: Prikaži status komande
      ansible.builtin.debug:
        var: ps_out.stdout_lines
