- name: Kreiraj AD grupu "test" bez DC i bez -NoProfile
  hosts: Management_Servers
  gather_facts: no

  tasks:
    - name: Pokreni PowerShell komandu za proveru i kreiranje AD grupe
      ansible.windows.win_shell: |
        Import-Module ActiveDirectory
        Start-Sleep -Seconds 2

        $groupName = "test"
        $ouPath = "OU=YU,OU=BAT Groups,DC=Global,DC=batgen,DC=com"
        New-ADGroup -Name $groupName `
                        -SamAccountName $groupName `
                        -GroupScope Global `
                        -GroupCategory Security `
                        -Path $ouPath
    
     
      register: ad_group_result

    - name: Prikaži rezultat
      debug:
        var: ad_group_result.stdout_lines
