---
- name: Kreiraj AD grupu lokalno sa RSAT-om
  hosts: Management_server
  gather_facts: no
  tasks:
    - name: Kreiraj AD grupu preko PowerShell-a
      ansible.windows.win_shell: |
        Import-Module ActiveDirectory
        $groupName = "test"
        $path = "OU=YU,OU=BAT Groups,DC=Global,DC=batgen,DC=com"
        if (-not (Get-ADGroup -LDAPFilter "(cn=$groupName)" -ErrorAction SilentlyContinue)) {
          New-ADGroup -Name $groupName -GroupScope Global -GroupCategory Security -Path $path
          Write-Output "Grupa kreirana"
        } else {
          Write-Output "Grupa već postoji"
        }
