---
- name: Install VMware Tools silently without forcing reboot
  hosts: Test
  gather_facts: no

  tasks:
    - name: Run VMware Tools setup silently
      win_shell: |
        $setupPath = 'C:\temp\ansible\vmwaretools\setup.exe'
        Start-Process -FilePath $setupPath -ArgumentList '/S /v"/qn"' -Wait
      args:
        executable: powershell.exe
