- name: Install VMware Tools silently with reboot
  hosts: Test
  gather_facts: no
  tasks:
    - name: Run VMware Tools setup silently with reboot
      win_shell: |
        $setupPath = 'C:\temp\ansible\vmwaretools\setup.exe'
        Start-Process -FilePath $setupPath -ArgumentList '/S /v"/qn REBOOT=FORCE"' -Wait
      args:
        executable: powershell.exe
