- name: Run basic PowerShell script and show output
  hosts: UPIS_Plate
  tasks:
    - name: Echo
      ansible.windows.win_powershell:
        script: |
          echo "Hello World"
          echo "whoami"
          echo "ping 10.176.26.90"
      register: ps_output

    - name: Show PowerShell output
      debug:
        var: ps_output.output
