- name: Run basic PowerShell script and show output
  hosts: all
  tasks:
    - name: Echo
      ansible.windows.win_powershell:
        script: |
          winrm delete winrm/config/Listener?Address=*+Transport=HTTPS
            register: ps_output

    - name: Show PowerShell output
      debug:
        var: ps_output.output
