---
- name: Set WinHTTP proxy on Windows hosts
  hosts: all
  gather_facts: no
  tasks:
    - name: Set WinHTTP proxy using netsh
      ansible.windows.win_shell: >
        netsh winhttp set proxy
        proxy-server=http://aproxy1.global.batgen.com:9400
        bypass-list=http://wsus_az
      register: netsh_result

    - name: Show command output
      debug:
        var: netsh_result.stdout
