- name: Install and run PSWindowsUpdate module
  hosts: all
  gather_facts: no
  become: yes
  become_method: runas
  become_user: SYSTEM

  tasks:
    - name: Install and run Windows Updates (via WSUS)
      win_shell: |
        Import-Module PSWindowsUpdate
        Get-WindowsUpdate -AcceptAll -Install -IgnoreReboot

    - name: Reboot immediately after update
      win_reboot:
        reboot_timeout: 1800
