---
- name: Install and run PSWindowsUpdate module
  hosts: all
  gather_facts: no
  tasks:

    - name: Import module and run Windows Update (using WSUS)
      win_shell: |
        Import-Module PSWindowsUpdate
        Get-WindowsUpdate -AcceptAll -Install -IgnoreReboot

    - name: Reboot if required
      win_reboot:
        reboot_timeout: 1800
        test_command: '[System.IO.File]::Exists("C:\Windows\Temp\RebootRequired.flag")'
      register: reboot_result
