---
- name: List downloaded but not installed updates
  hosts: all
  gather_facts: no
  tasks:
    - name: Check pending install updates
      win_shell: |
        $session = New-Object -ComObject Microsoft.Update.Session
        $searcher = $session.CreateUpdateSearcher()
        $searchResult = $searcher.Search("IsInstalled=0 and IsDownloaded=1")
        $titles = $searchResult.Updates | ForEach-Object { $_.Title }
        $titles -join "`n"
      register: pending_updates

    - name: Show pending install updates
      debug:
        var: pending_updates.stdout_lines
