---
- name: Force WSUS updates via PowerShell
  hosts: windows_servers
  gather_facts: no
  tasks:

    - name: Trigger WSUS scan and install
      win_shell: |
        UsoClient.exe StartScan
        UsoClient.exe StartDownload
        UsoClient.exe StartInstall
        Start-Sleep -Seconds 60
        $RebootRequired = (Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired" -ErrorAction SilentlyContinue)
        if ($RebootRequired) {
            Restart-Computer -Force
        }
