---
- name: Install Windows Updates via WSUS on Windows Server 2016
  hosts: windows_servers
  gather_facts: false
  tasks:
    - name: Install approved updates from WSUS
      ansible.windows.win_updates:
        state: installed
        server_selection: managed_server
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
        accept_list: []
        reject_list: []
        reboot: true
        reboot_timeout: 1800
        skip_optional: true
      register: update_result

    - name: Show updates that were installed
      debug:
        var: update_result
