- name: Fully update Windows servers until no updates remain
  hosts: Test
  gather_facts: no
  vars:
    max_iterations: 5   # maksimalno ponavljanja da se izbegne beskonačna petlja
  tasks:

    - name: Loop to install updates until none remain
      block:
        - name: Stop Windows Update service
          ansible.windows.win_service:
            name: wuauserv
            state: stopped

        - name: Clear Windows Update cache
          ansible.windows.win_shell: Remove-Item -Path "C:\Windows\SoftwareDistribution\Download\*" -Recurse -Force

        - name: Start Windows Update service
          ansible.windows.win_service:
            name: wuauserv
            state: started

        - name: Install all available updates
          ansible.windows.win_updates:
            category_names: '*'
            reboot: yes
            reboot_timeout: 600
          register: update_result

        - name: Wait for reboot if required
          ansible.windows.win_reboot:
            reboot_timeout: 600
          when: update_result.reboot_required

        - name: Check for remaining updates
          ansible.windows.win_updates:
            category_names: '*'
          register: check_updates

        - name: Show remaining updates
          debug:
            var: check_updates.updates

      loop: "{{ range(1, max_iterations + 1) | list }}"
      loop_control:
        label: "Update iteration {{ item }}"
      when: check_updates is not defined or check_updates.updates | length > 0
