---
- hosts: windows_servers
  tasks:
    - name: Install Windows Updates
      ansible.windows.win_updates:
        category_names:
          - 'Critical Updates'
          - 'Security Updates'
          - 'Update Rollups'
        reboot: yes
        reboot_timeout: 600
      register: update_result

    - name: Reboot if required
      ansible.windows.win_reboot:
        reboot_timeout: 600
      when: update_result.reboot_required
