---
- name: Check available Windows Updates using PSWindowsUpdate
  hosts: all
  gather_facts: no
  tasks:
    - name: List available updates
      win_shell: |
        Import-Module PSWindowsUpdate
        Get-WindowsUpdate -AcceptAll -IgnoreReboot -WhatIf | Out-String
      register: update_result

    - name: Show available updates
      debug:
        var: update_result.stdout_lines
