---
- name: Install all available Windows Updates
  hosts: windows
  gather_facts: no
  tasks:
    - name: Install all available updates and reboot if needed
      ansible.windows.win_updates:
        category_names: ['CriticalUpdates', 'SecurityUpdates', 'UpdateRollups']
        state: installed
        reboot: yes
      register: update_result

    - name: Show update installation result
      debug:
        var: update_result
