---
- name: Install all Windows updates and reboot as needed
  hosts: all
  gather_facts: no
  tasks:
    - name: Install all updates and reboot as many times as needed
      ansible.windows.win_updates:
        category_names: '*'
        reboot: true
