- name: Play koji se izvršava kao admin
  hosts: all
  gather_facts: no
  become: yes
  become_method: runas
  become_user: Administrator
  tasks:
    - name: Primer - instaliraj update
      ansible.windows.win_updates:
        category_names: ['CriticalUpdates', 'SecurityUpdates', 'UpdateRollups', 'Updates']
        state: installed
        reboot: yes
      register: update_result
