- name: List available WSUS-approved updates
  hosts: all
  gather_facts: no
  tasks:
    - name: Get available updates
      ansible.windows.win_updates:
        category_names: '*'
        state: searched
      register: update_info

    - name: Show available updates
      debug:
        var: update_info.updates
