- name: Fully update Windows servers until no updates remain
  hosts: Test
  gather_facts: no
  vars:
    max_retries: 5
    delay_between_retries: 60
  tasks:

    - name: Stop Windows Update service
      ansible.windows.win_service:
        name: wuauserv
        state: stopped

    - name: Clear Windows Update cache
      ansible.windows.win_shell: Remove-Item -Path "C:\Windows\SoftwareDistribution\Download\*" -Recurse -Force

    - name: Start Windows Update service
      ansible.windows.win_service:
        name: wuauserv
        state: started

    - name: Install all available updates
      ansible.windows.win_updates:
        category_names: '*'
        reboot: yes
        reboot_timeout: 600
      register: update_result
      until: update_result.updates | length == 0
      retries: "{{ max_retries }}"
      delay: "{{ delay_between_retries }}"

    - name: Show remaining updates
      ansible.windows.win_updates:
        category_names: '*'
      register: check_updates

    - name: Debug remaining updates
      debug:
        var: check_updates.updates
