---
- name: Install Windows Updates via WSUS
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Install approved updates from WSUS
      ansible.windows.win_updates:
        state: installed
        server_selection: managed_server
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
        accept_list: []   # Optional: Add KBs or patterns
        reject_list: []   # Optional: Exclude specific updates
        reboot: true
        reboot_timeout: 1800
        skip_optional: true
      register: update_result

    - name: Show updates that were installed
      debug:
        var: update_result
