---
- name: Sync WSUS and install available updates
  hosts: windows
  gather_facts: no
  tasks:
    - name: Force WSUS detection
      win_shell: wuauclt /detectnow

    - name: Wait 60 seconds for WSUS sync
      pause:
        seconds: 60

    - name: Install available WSUS-approved updates and reboot if needed
      ansible.windows.win_updates:
        category_names: ['CriticalUpdates', 'SecurityUpdates', 'UpdateRollups', 'Updates']
        state: installed
        reboot: yes
      register: update_result

    - name: Show update installation result
      debug:
        var: update_result
